# Generated by Django 4.1.4 on 2023-02-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_city_alter_shippingaddress_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customers',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customers',
            name='email',
        ),
        migrations.AddField(
            model_name='customers',
            name='last_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Elektron manzil'),
            preserve_default=False,
        ),
    ]
